package com.nextstepsenegal.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConseillerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConseillerAllPropertiesEquals(Conseiller expected, Conseiller actual) {
        assertConseillerAutoGeneratedPropertiesEquals(expected, actual);
        assertConseillerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConseillerAllUpdatablePropertiesEquals(Conseiller expected, Conseiller actual) {
        assertConseillerUpdatableFieldsEquals(expected, actual);
        assertConseillerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConseillerAutoGeneratedPropertiesEquals(Conseiller expected, Conseiller actual) {
        assertThat(expected)
            .as("Verify Conseiller auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConseillerUpdatableFieldsEquals(Conseiller expected, Conseiller actual) {
        assertThat(expected)
            .as("Verify Conseiller relevant properties")
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getPrenom()).as("check prenom").isEqualTo(actual.getPrenom()))
            .satisfies(e -> assertThat(e.getSpecialite()).as("check specialite").isEqualTo(actual.getSpecialite()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getCertifie()).as("check certifie").isEqualTo(actual.getCertifie()))
            .satisfies(e -> assertThat(e.getPassword()).as("check password").isEqualTo(actual.getPassword()))
            .satisfies(e -> assertThat(e.getPasswordHash()).as("check passwordHash").isEqualTo(actual.getPasswordHash()))
            .satisfies(e -> assertThat(e.getKeycloakId()).as("check keycloakId").isEqualTo(actual.getKeycloakId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConseillerUpdatableRelationshipsEquals(Conseiller expected, Conseiller actual) {
        // empty method
    }
}
