package com.nextstepsenegal.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EleveAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEleveAllPropertiesEquals(Eleve expected, Eleve actual) {
        assertEleveAutoGeneratedPropertiesEquals(expected, actual);
        assertEleveAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEleveAllUpdatablePropertiesEquals(Eleve expected, Eleve actual) {
        assertEleveUpdatableFieldsEquals(expected, actual);
        assertEleveUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEleveAutoGeneratedPropertiesEquals(Eleve expected, Eleve actual) {
        assertThat(expected)
            .as("Verify Eleve auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEleveUpdatableFieldsEquals(Eleve expected, Eleve actual) {
        assertThat(expected)
            .as("Verify Eleve relevant properties")
            .satisfies(e -> assertThat(e.getNom()).as("check nom").isEqualTo(actual.getNom()))
            .satisfies(e -> assertThat(e.getPrenom()).as("check prenom").isEqualTo(actual.getPrenom()))
            .satisfies(e -> assertThat(e.getDateNaissance()).as("check dateNaissance").isEqualTo(actual.getDateNaissance()))
            .satisfies(e -> assertThat(e.getTelephone()).as("check telephone").isEqualTo(actual.getTelephone()))
            .satisfies(e -> assertThat(e.getAdresse()).as("check adresse").isEqualTo(actual.getAdresse()))
            .satisfies(e -> assertThat(e.getEmail()).as("check email").isEqualTo(actual.getEmail()))
            .satisfies(e -> assertThat(e.getSerie()).as("check serie").isEqualTo(actual.getSerie()))
            .satisfies(e -> assertThat(e.getNiveauEtude()).as("check niveauEtude").isEqualTo(actual.getNiveauEtude()))
            .satisfies(e -> assertThat(e.getLycee()).as("check lycee").isEqualTo(actual.getLycee()))
            .satisfies(e -> assertThat(e.getVille()).as("check ville").isEqualTo(actual.getVille()))
            .satisfies(e -> assertThat(e.getPassword()).as("check password").isEqualTo(actual.getPassword()))
            .satisfies(e -> assertThat(e.getPasswordHash()).as("check passwordHash").isEqualTo(actual.getPasswordHash()))
            .satisfies(e -> assertThat(e.getKeycloakId()).as("check keycloakId").isEqualTo(actual.getKeycloakId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEleveUpdatableRelationshipsEquals(Eleve expected, Eleve actual) {
        // empty method
    }
}
