package com.nextstepsenegal.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PublicationShareAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationShareAllPropertiesEquals(PublicationShare expected, PublicationShare actual) {
        assertPublicationShareAutoGeneratedPropertiesEquals(expected, actual);
        assertPublicationShareAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationShareAllUpdatablePropertiesEquals(PublicationShare expected, PublicationShare actual) {
        assertPublicationShareUpdatableFieldsEquals(expected, actual);
        assertPublicationShareUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationShareAutoGeneratedPropertiesEquals(PublicationShare expected, PublicationShare actual) {
        assertThat(expected)
            .as("Verify PublicationShare auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationShareUpdatableFieldsEquals(PublicationShare expected, PublicationShare actual) {
        assertThat(expected)
            .as("Verify PublicationShare relevant properties")
            .satisfies(e -> assertThat(e.getUserId()).as("check userId").isEqualTo(actual.getUserId()))
            .satisfies(e -> assertThat(e.getUserType()).as("check userType").isEqualTo(actual.getUserType()))
            .satisfies(e -> assertThat(e.getSharedAt()).as("check sharedAt").isEqualTo(actual.getSharedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationShareUpdatableRelationshipsEquals(PublicationShare expected, PublicationShare actual) {
        assertThat(expected)
            .as("Verify PublicationShare relationships")
            .satisfies(e -> assertThat(e.getPublication()).as("check publication").isEqualTo(actual.getPublication()));
    }
}
