package com.nextstepsenegal.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PublicationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationAllPropertiesEquals(Publication expected, Publication actual) {
        assertPublicationAutoGeneratedPropertiesEquals(expected, actual);
        assertPublicationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationAllUpdatablePropertiesEquals(Publication expected, Publication actual) {
        assertPublicationUpdatableFieldsEquals(expected, actual);
        assertPublicationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationAutoGeneratedPropertiesEquals(Publication expected, Publication actual) {
        assertThat(expected)
            .as("Verify Publication auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationUpdatableFieldsEquals(Publication expected, Publication actual) {
        assertThat(expected)
            .as("Verify Publication relevant properties")
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()))
            .satisfies(e -> assertThat(e.getAuthorId()).as("check authorId").isEqualTo(actual.getAuthorId()))
            .satisfies(e -> assertThat(e.getAuthorType()).as("check authorType").isEqualTo(actual.getAuthorType()))
            .satisfies(e -> assertThat(e.getCreatedAt()).as("check createdAt").isEqualTo(actual.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationUpdatableRelationshipsEquals(Publication expected, Publication actual) {
        // empty method
    }
}
