package com.nextstepsenegal.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PublicationLikeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationLikeAllPropertiesEquals(PublicationLike expected, PublicationLike actual) {
        assertPublicationLikeAutoGeneratedPropertiesEquals(expected, actual);
        assertPublicationLikeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationLikeAllUpdatablePropertiesEquals(PublicationLike expected, PublicationLike actual) {
        assertPublicationLikeUpdatableFieldsEquals(expected, actual);
        assertPublicationLikeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationLikeAutoGeneratedPropertiesEquals(PublicationLike expected, PublicationLike actual) {
        assertThat(expected)
            .as("Verify PublicationLike auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationLikeUpdatableFieldsEquals(PublicationLike expected, PublicationLike actual) {
        assertThat(expected)
            .as("Verify PublicationLike relevant properties")
            .satisfies(e -> assertThat(e.getUserId()).as("check userId").isEqualTo(actual.getUserId()))
            .satisfies(e -> assertThat(e.getUserType()).as("check userType").isEqualTo(actual.getUserType()))
            .satisfies(e -> assertThat(e.getLikedAt()).as("check likedAt").isEqualTo(actual.getLikedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPublicationLikeUpdatableRelationshipsEquals(PublicationLike expected, PublicationLike actual) {
        assertThat(expected)
            .as("Verify PublicationLike relationships")
            .satisfies(e -> assertThat(e.getPublication()).as("check publication").isEqualTo(actual.getPublication()));
    }
}
